#!/bin/sh

AWKCMD="\$1 == \"$1\" {print \"mysql --quick --compress --local-infile=1 --host=
\" \$4 \" --user=\" \$2 \" --password=\" \$3 \" \" \$1}"
AWKRESULT=`cat ~/.dbrc | awk "$AWKCMD"`
$AWKRESULT
